{% set name = "jupyterlab-niryo-one" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab_niryo_one-{{ version }}.tar.gz
  sha256: 65ae8ec54321cdfdbc01b5e3d93731d8656e34cd4737cd39b5775819097bb8b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter_packaging
    - pip
    - python >=3.7
  run:
    - jupyterlab-blockly >=0.1.0a5,<0.2
    - python >=3.7

test:
  imports:
    - jupyterlab_niryo_one
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantstack/jupyterlab-niryo-one
  summary: Blockly extension for JupyterLab to control the Niryo One robot.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
