{% set name = "jupyterlab-niryo-one" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jupyter-robotics/{{ name }}/releases/download/v{{ version }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 65ae8ec54321cdfdbc01b5e3d93731d8656e34cd4737cd39b5775819097bb8b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.8
    - hatchling >=1.5.0
    - hatch-nodejs-version >=0.3.2
    - hatch-jupyter-builder
  run:
    - jupyterlab-blockly >=0.3.3,<0.4
    - python >=3.8

test:
  imports:
    - jupyterlab_niryo_one
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantstack/jupyterlab-niryo-one
  summary: Blockly extension for JupyterLab to control the Niryo One robot.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DenisaCG
    - hbcarlos
